services:
  api:
    build: .
    container_name: mock_api
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=app/main.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://mock_user:mock_pass@db:5432/mock_db
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: mock_db
    environment:
      POSTGRES_USER: mock_user
      POSTGRES_PASSWORD: mock_pass
      POSTGRES_DB: mock_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-multiple-dbs.sql:/docker-entrypoint-initdb.d/init-multiple-dbs.sql


  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mock.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  pgdata:
