"""create mock_config table

Revision ID: 2a1e8597cdc7
Revises: 
Create Date: 2025-07-09 07:43:48.549607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2a1e8597cdc7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mock_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('query_params', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('body_params', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('headers', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_body', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('delay_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mock_configs')
    # ### end Alembic commands ###
